### ISSUE TITLE
Cannot view sub channels in channel browser

### ISSUE THREAD

**Issue by Brandoskey** [ILadis/ts3-qs4sd#16]
My server has a number of sub channels and thus far I do not see a way to join these without possibly following another user in first

**Comment by ILadis** [comment]
Thank you for the bug report.

So the channel browser is not displaying your servers channel layout correctly? Are channels missing or is the channel hierarchy displayed wrong?

Could you post a screenshot of your servers channel layout? And also a screenshot of the server browser of the Decky plugin. Feel free to mask/cover parts of the channel names.

If it's not obvious from the screenshots, please state what channels are missing.

**Comment by Brandoskey** [comment]
The plugin only displays top level channels. In the screenshots below, all the channels under The Pond are not visible in the plugin. This is the case for all nested/sub channels

![steamuserimages-a akamaihd](https://github.com/user-attachments/assets/f861a749-41ef-4eb7-bca0-a1b6a8c71d10)
![ts3-snip](https://github.com/user-attachments/assets/e6a9e87f-ee88-42c5-8c45-7334359f619a)

**Comment by ILadis** [comment]
The channel browser is currently programmed to distinguish between "joinable channels" and "non joinable channels". This difference is determined by the "maximum number of clients" a channel can hold. The "expand button" is displayed to the left of any "non joinable channels".

So in order for the channel browser to display a channel as a "sub channel" it has to be set to hold 0 clients:  
![Screenshot](https://github.com/user-attachments/assets/5f2ba608-f3a7-42d9-a506-392bac57aaaf)

So for the time being you need to change the channel settings if you want them being displayed as "sub channels".

A better way of determining "sub channels" in the future may be to check if a channel actually has sub channels and not relying on the "maximum number of clients" setting.

I'm going to work on this and change the way "sub channels" are determined. I'll leave this issue open until it's "fixed".

**Comment by Brandoskey** [comment]
The way the server is setup the higher level channels are where people start out and then break off into the sub channels, so limiting them to 0 users would be an issue.

An update on the logic would be greatly appreciated, thanks for looking into this.

**Comment by ILadis** [comment]
Hey @Brandoskey, there's a new development build available which should fix your issue. This version now actually checks for the presence of sub channels and doesn't rely on the "maximum number of clients" setting anymore.

You can [download this pre-release from here](https://github.com/ILadis/ts3-qs4sd/releases/tag/latest). You need to install the `plugin.zip` manually from the DeckyLoader settings.

Once you confirm that this version indeed fixes the issue, I'll prepare a pull request to get the fix to the official store.

**Comment by Brandoskey** [comment]
I downloaded the dev version from your link to the steam deck and tried to install it as a zip in deckyloader however nothing happens. I uninstalled the version I had installed and tried again and still nothing.

I enabled dev mode in decky to perform the install. Maybe there's some other way?

**Comment by Brandoskey** [comment]
I got a little further, after installing the latest pre-release version of decky I got a progress bar upon installing the zip, however it stops at roughly 95% hangs there seemingly forever

**Comment by ILadis** [comment]
Decky's install from ZIP file option is a hit or miss. You can try manually unzipping the file. To do this, switch to desktop mode. All plugins go in `/home/deck/homebrew/plugins` if I'm not mistaken. Just unzip the `plugin.zip` file there (you should find folders for all your other installed plugin there aswell).

**Comment by Brandoskey** [comment]
Extracted plugin.zip to my plugins folder and it doesn't show up in decky. Tried a reboot but no luck. Is it possible something is wrong with the build?

**Comment by ILadis** [comment]
You are right, the automatic build did not produce a valid `plugin.zip`, there were some files missing. Sorry for that.

Should be fixed now. There's a new pre-release available for you to try.

**Comment by Brandoskey** [comment]
I was able to get this latest build installed by unzip through terminal and restarting. I can confirm all sub channels now work.

I also noticed an option for choosing a microphone under settings. I assume that's new too?

Thanks for this update, it's working well.

**Comment by ILadis** [comment]
Glad to hear the updated version is working for you. And yes, the microphone settings is a new feature in the upcoming 1.2.0 release.

I've updated the current [pending pull request](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/670) for version 1.2.0 to include the fix for the channel browser.

I'm going to ping you again, once this version is available in the Decky tesing store. It would be really helpful if you could then [post a testing report](https://wiki.deckbrew.xyz/en/user-guide/testing#submitting-a-test-report) in the linked pull request.
