### ISSUE TITLE
Steam Deck freezes after klicking on TS3 icon

### ISSUE THREAD

**Issue by Binger95** [ILadis/ts3-qs4sd#2]
Hey there,

I have an issue. I did everything in the installing guide. But at the end when I klick on the Teamspeak Icon my Steam Deck freezes. Do u have any idea why this is? Or is this something u have seen already? Or do I need to do something additionally to the installation guide? If u need more information tell me what u need.

Thank you for your help and making this Plugin! 

Greetings

**Comment by ILadis** [comment]
After you setup everything in desktop mode and switched back to gaming mode, you are supposed to do the following:

1. Launch TeamSpeak from gaming mode
2. You should see the TeamSpeak interface
3. Hit the Steam button on your Deck
4. Select Home to go back to your game library

By doing this you essentially have TeamSpeak running in the background and are able to launch the game of your choice.

Is it really freezing after doing 2? You are not able to interact with the TeamSpeak interface in gaming mode.

**Comment by Binger95** [comment]
Thanks for the fast reply!
Its freezing after doing 4. I´m back into the game library. When I wanna join on a Server that I bookmarked, I see the Server but when I press A its freezing. Have to hold Steam button to get out of it.

**Comment by ILadis** [comment]
You have to use the touchscreen to navigate within the quick access menu. The controller buttons are not working (yet).

**Comment by Binger95** [comment]
It´s working! Should have tried this... I´m used to the buttons more than to the touchscreen. Never thought on it. Thank you very much!

**Comment by ILadis** [comment]
Yea, it's a bit inconvenient. Glad it's working though.
