### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by Hellangel1987** [ILadis/ts3-qs4sd#4]
Install not working as in readme - still tried to install the zip file from Github. Nothing happens.

Any suggestions?

**Comment by Hellangel1987** [comment]
still tried manual installation with copy zip file - and also tried installation via 3rd party in decky loader not working.

plugin not showing up and not loading

**Comment by ILadis** [comment]
It's working for me.  
My plugin is now also available in the testing store. You can switch to the testing store and install it from there.

If you installed the plugin from the testing store, and had no issues, please write a comment in this [pull request](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/401). This would help me get the plugin to the official store. You can find more information on testing Decky plugins [here](https://decky.xyz/testing).


<details><summary>If you want to try install the plugin manually, these are the steps I usually do.</summary>

* Switch to desktop mode and open a terminal
* Download the plugin: `curl -OL https://github.com/ILadis/ts3-qs4sd/releases/download/v1.0.0/plugin.zip`
* Change working directory to Decky plugins: `cd ~/homebrew/plugins`
* Make the directory writable: `chmod +w .`
* Extract the plugin: `unzip ~/plugin.zip`

After extracting the archive check if it successfully created the `ts3-qs4sd` folder in the `plugins/` directory:

```sh
$ ls -al
total 12K
drwxr-xr-x 3 deck deck 4.0K Jul 16 21:30 .
drwxr-xr-x 7 deck deck 4.0K Jul  9 01:06 ..
dr-xr-xr-x 5 deck deck 4.0K Jul 16 21:30 ts3-qs4sd
```
</details>

**Comment by Hellangel1987** [comment]
works via installation with Test Decky Store - Manual install failed several times by myside.

looking forward for the slider to start Teamspeak :)

**Comment by ILadis** [comment]
Alright, glad it worked.

If you want to leave a testing report feel free to do so in this [pull request](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/401). You can find more information on testing Decky plugins [here](https://decky.xyz/testing).
