### ISSUE TITLE
feature request: view empty Channels

### ISSUE THREAD

**Issue by DSKB823** [ILadis/ts3-qs4sd#6]
Is there a chance that we'll see an option to show empty channels in the plugin in the future? 

I'm thinking simply a single button/checkbox to show all the channels the Server has, so users can easier switch channels without waiting for others to switch first. 
They could toggle the button again afterwards to keep their view nice and tidy while also not overburdening the UI with too many buttons/options or even an additional options menu. 

I personally could use the feature for 2 Reasons:
1. joining AFK channels when going AFK
2. My friends tend to wait in the AFK channel until I join a channel they can join, which right now would be only the AFK channel and whatever channel I have set in my Bookmark, which is manageable but not ideal.

If that's too much work, I completely understand, I just wanted to ask if it was possible and you'd be willing to add such a feature.

**Comment by ILadis** [comment]
Sounds like a usefull feature to have. I'm currently thinking of a button *"View all Channels"* which would open a separate dialog containing a tree view of all available channels. One could then select a channel to join it.

I am putting this on my TODO list for the next release. But I can't say when that version will be available.

**Comment by DSKB823** [comment]
I could see that working from a function as well as from a design pov. Just mention me in your next releases PR whenever you get around to it and I'll gladly provide the Test Report again.

**Comment by ILadis** [comment]
> Just mention me in your next releases PR whenever you get around to it and I'll gladly provide the Test Report again.

Sure will do. Appreciate your help!

**Comment by ILadis** [comment]
Hey @DSKB823, I've got a new development release of the plugin ready which includes the channel browser you requested. It's not the prettiest but get's the job done.

You can download the current pre release of version 1.1.3 of the plugin [here](https://github.com/ILadis/ts3-qs4sd/files/13326358/plugin.zip).

I'm not particular happy with how the navigation is currently handled inside of the channel browser. If you have any suggestions or feedback, please let me know!

**Comment by DSKB823** [comment]
Okay I think I got a few Ideas for the channel browser. Any chance we could talk about that in private? I took a few screenshots and made a quick mockup but I'd need to censor both quite heavily since this account is supposed to be hard to connect to my IRL and online  presence.

**Comment by ILadis** [comment]
Sure, how do you want to get in touch?

**Comment by DSKB823** [comment]
I think I just messaged you on Discord.

**Comment by wizzardyno** [comment]
Hey, your plugin does not see empty channels, and there is also no way to join a channel that will provide a password, my friends and I have a server where everyone has their own channel with a password, I would like you to try to make it possible to enter a password when entering the channel. Thanks for your work.

**Comment by ILadis** [comment]
Thanks for pointing out that you currently cannot join password protected channels. I think I can also support this with the next update.

The current proposal for the upcoming version looks like this:

![Mockup](https://github.com/ILadis/ts3-qs4sd/assets/7196536/83414a84-881d-4276-bacd-46fc3988ddcd)

This is just a mockup of how the UI is going to look like. As you can see there will be a dedicated view for the channel browser. This will make it possible to browse and join all (including empty) channels.

**Comment by ILadis** [comment]
I've got a new version of the plugin ready which implements both the channel browsers (as shown in the screenshot) and a password prompt for protected channels.

Please give this one a test!  
You can download the new version [here](https://github.com/ILadis/ts3-qs4sd/files/13620554/plugin.zip).

If you have any feedback or encounter any errors/bugs, please let me know!

**Edit**:  
I built a faulty version, which made the plugin unusable after installation. I updated the download link, it now points to the correct version.

**Comment by ILadis** [comment]
I created a [pull request](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/485) for the new version. Once it's available in the testing store please post your testing reports [here](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/485).

I'm considering this issue as resolved.
