### ISSUE TITLE
How to get Push-to-Talk running?

### ISSUE THREAD

**Issue by getNovsky** [ILadis/ts3-qs4sd#7]

**Comment by ILadis** [comment]
Have you already tried what's written in the `README.md`?

> If you want to use Push-to-Talk allow TeamSpeak to access your Steam Deck inputs: `flatpak override --user com.teamspeak.TeamSpeak --device=all`

This essentially means that you are supposed to switch to Desktop mode and run this command in a terminal:

```sh
flatpak override --user com.teamspeak.TeamSpeak --device=all
```

After doing so Push-to-Talk should be enabled. It's currently bound to L5 and cannot be assigned to a different button. Once you hit L5 TeamSpeak should switch to Push-to-Talk mode, if I remember correctly.

**Comment by getNovsky** [comment]
Tx for the fast response.

I reinstalled TeamSpeak and TS3 Overlay with using the command but still in voice activation mode

**Comment by ILadis** [comment]
Please verify that the flatpak override is set correctly. To do so, post the output of this command:

```sh
flatpak override --user --show com.teamspeak.TeamSpeak
```

Please also have a look in the TeamSpeak 3 "Client Log" window. To do this, switch to Desktop mode and open TeamSpeak. Then click on Tools > Client Log.

Now press the L5 button on your Deck. It should show a logging output in the "Client Log" window like this:

![Screenshot](https://github.com/ILadis/ts3-qs4sd/assets/7196536/a244157e-820d-4f34-90b6-da374a86638d)

The message to look out for is: `"L5 button is held: PTT active"`

**Comment by getNovsky** [comment]
![PXL_20231210_224230302](https://github.com/ILadis/ts3-qs4sd/assets/40595821/8ec95b20-c5c1-46a1-a701-e876fdd3cee8)
![PXL_20231210_224158965](https://github.com/ILadis/ts3-qs4sd/assets/40595821/05b09742-a8a3-4e8b-a0de-f7f320da1fbc)
![PXL_20231210_224101646](https://github.com/ILadis/ts3-qs4sd/assets/40595821/0adaed71-b6a7-4563-9048-a89048703546)
![PXL_20231210_222955292](https://github.com/ILadis/ts3-qs4sd/assets/40595821/cd5c3c6c-667a-4401-985d-e8b5ed566457)


I tested the command like you said. See result picture.

In desktop I can use the l5 key, which is mounted to the "windows system key" but no info in the client log. The push to talk works on desktop but not in steam.

**Comment by ILadis** [comment]
Sorry for the late response (been busy).

Thanks for providing all these screenshots. I can't see the message I'm looking for in the images that show the TeamSpeak Client Log window. As I said, the message to look for reads: `"L5 button is held: PTT active"`.

To make sure everything is working, could you please make sure, this message appears when you hold down the L5 button on your Deck?

Another problem with your current configuration is that you have Push-to-Talk enabled in the TeamSpeak settings. Please switch to "Continuous Transmission" ("Dauersenden"). By doing so the blue icon to the left of your nickname should light up. But once you press and release L5 it should switch off. If you press and hold L5 again it should switch on.

Here is a screenshot of my setup:

![Screenshot](https://github.com/ILadis/ts3-qs4sd/assets/7196536/d42f0855-f329-4508-8004-74f6d2c67f81)

**Comment by getNovsky** [comment]
![PXL_20231227_232413265](https://github.com/ILadis/ts3-qs4sd/assets/40595821/2e2fe84b-9798-40aa-a1b7-6243bcb7f0fd)

There is no L5 message. Only the error about the steam input device.

**Comment by ILadis** [comment]
Thats actually a good hint on where to look next.

I suspect that the way my plugin currently looks for the Steam Deck input device is too specific and may not work on every device. In one of my latest commits I changed this to be less specific and also added some extra debug logs.

Could you please try the latest development build from today? You can download the `plugin.zip` from the releases page [here](https://github.com/ILadis/ts3-qs4sd/releases/tag/latest). If you need instructions on how to manually install a plugin have a look at the [README](https://github.com/ILadis/ts3-qs4sd/blob/master/README.md#installing).

Once this version is installed please switch to desktop mode and verify that the plugin is now at version 1.1.4 (Tools > Options > Addons). Then again open the Client Log window and look for either error messages or try pressing L5 and see if `"L5 button is held: PTT active"` pops up.

**Comment by getNovsky** [comment]
Hey, I installed your developer release and the L5 works fine now. 

If I can help you with a recommendation or log files, give me a hint. 

Thank you very much for the plugin, your fast and successful help.

 I wish you a happy new year

**Comment by ILadis** [comment]
Glad this fixed your issue. If it is working for you now, I don't need screenshots or log files anymore.

I don't know when I can release an "official" version with this fix in the Decky store. But until then you can just keep using the development version.

Happy new year to you as well.
