### ISSUE TITLE
The discovery store changed to TeamSpeak 5

### ISSUE THREAD

**Issue by AU518987077** [ILadis/ts3-qs4sd#9]
the plugin does not seem to function any more due to this change
hopefully this is easy, or diffucult to fix, and not impossible at this time.

**Comment by ILadis** [comment]
I'm definitely going to look into this. But I'm not sure if TeamSpeak 5 has support for third party plugins yet.

If you want a workaround, you can still install TeamSpeak 3 on your Deck. To do so, first uninstall TeamSpeak 5 through the discover store. Then run the following commands in a terminal:

```sh
$ flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak install --user com.teamspeak.TeamSpeak
$ flatpak update --user --commit=af1df787d5aecf0473dd93a98ed3fa728da9488050aa93253cd4b7dbe89f61ea com.teamspeak.TeamSpeak
```

If you have root access on your Deck enabled, you don't need to install TeamSpeak in "user mode" and are able to downgrade immediately (without uninstalling TeamSpeak 5 first), by running:

```sh
$ sudo flatpak update --commit=af1df787d5aecf0473dd93a98ed3fa728da9488050aa93253cd4b7dbe89f61ea com.teamspeak.TeamSpeak
```

**Comment by duumxh** [comment]
TeamSpeak3 has been released as separate package on flathub [link](https://github.com/flathub/com.teamspeak.TeamSpeak3)

Directory has been changed from TeamSpeak to TeamSpeak3, therefore plugin can't find TeamSpeak's location to install the addon. 

Should be easy to fix 😊

**Comment by wx40217** [comment]
When I opened the plugin I found that nothing showed up.I then realized that I had upgraded my ts3 to ts5, and then tried installing ts3 (coexisting with ts5) and uninstalling ts5 leaving only ts3. but still nothing shows up.Is it possible that the data left behind by the uninstallation of ts5 is affecting the plugin?

**Comment by ILadis** [comment]
Thanks @DuumXH for this hint!

I've updated the plugin to be compatible with the dedicated TeamSpeak 3 version on FlatHub. You can try [the latest pre-release version](https://github.com/ILadis/ts3-qs4sd/releases/tag/latest) or wait for the official version from the store.

So as of know the plugin will only work if you've installed TeamSpeak 3 from the Discover store.  
It's **not** compatible with TS5!

I'm leaving this issue open until someone confirms, that the latest pre-release is working.  
But from my testing the new version should work just fine.

**Comment by LittleFreak** [comment]
Doesn't work for me. The TS3 plugin tab remains empty, despite the fact, that I'm connected with the server in the new TS3 flatpack.

**Comment by ILadis** [comment]
Can you please run the following command in a terminal in desktop mode and post the output:
```sh
$ flatpak list
```

Also make sure that you correctly installed version 1.1.4 of the plugin. You can do this by launching TeamSpeak 3 in desktop mode. Then open Settings > Options > Addons and check the version of the plugin.

**Edit**:  
Version 1.1.4 of the plugin is now also available in the Decky testing store. I started from a clean installation (no TS3 and plugin installed) and then downloaded the plugin from the store. Then switched to desktop mode and installed TS3 via:

```sh
$ flatpak install com.teamspeak.TeamSpeak3
```

After that I launched TeamSpeak 3 once from the application menu and added my bookmarks. Then switched back to gaming mode and all was set up.

**Comment by man-hein** [comment]
@ILadis i tested v1.1.4 from the decky store testing channel and it works for me, thank you 👍  i was also facing the issue that from discover, only teamspeak 5 was available for install. removed teamspeak 5 and followed these instructions (https://github.com/flathub/com.teamspeak.TeamSpeak3) to get back to version 3.

**Comment by ILadis** [comment]
Thanks for your feedback. Happy to hear that the latest version is working for you.

I would appreciate if you could post a testing report [on the pull request](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/526). This would help a lot getting the new version to the "official" store. You can read about testing reports on [this Decky wiki page](https://wiki.deckbrew.xyz/en/user-guide/testing).

I'm also considering this issue fixed.
